sudo: required
services:
  - docker

script:
  - docker build -t kipchichirian/node .
  - docker images kipchirchirian/node

before_deploy:
  - docker login -u kipchirchirian -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: docker push kipchirchirian/node
  on:
    branch: main